Henry-ecommerce/e-commerce-PF

client/src/App.js
client/src/Components/Product/Product.jsx

-Mando id en componente product.
-Agrego la ruta a ProductDetail en componente App.

Agrego faltantes que rompen

---

client/src/Components/ProductCarousel/Carousel.jsx
client/src/Components/ProductCarousel/Carousel.module.css

El componente Carousel, debería funcionar correctamente. incluye un pequeño comentario de como funciona.
-creados 2 elementos y una carpeta.
-ningún elemento modificado.

Creando componente carousel de productos

---

client/src/App.js
client/src/Components/AddToCardComponents/AddToCart.jsx
client/src/Components/AddToCardComponents/AddToCartIcon.jsx
client/src/Components/Navbar/Navbar.jsx
client/src/Components/Product/Product.jsx
client/src/Components/ProductDetails/ProductDetail.jsx

Agregados 2 componentes, Carrito Boton en forma de icono y Carrito Boton en string "Agregar al carrito".
Modificado el componente Product, saque la logica que agregaba al carrito, y reemplaze eso por el nuevo componente.
Cambios minimos en ProductDetail.
Cambios minimos en App.js
Cambio minimo en componente NavBar, ahora el iconito redirige correctamente al Login.

Componentes AddToCart para Utilizar en cualquier otra parte del Codigo.

---

client/src/Components/ProductDetails/ProductDetail.jsx
client/src/Components/ReviewCard/ReviewCard.jsx

- Se creo Componente Tarjeta Review para mostrar las Review de los usuarios
- En el Componente Product Detail se agrego el componete Tarjeta Review

Componente tarjeta review

---

api/src/Models/Categorias.js
api/src/Routes/Categories/indexCategories.js
api/src/Routes/index.js

Esta harcodeado igual que las rutas de productos, pero Messirve para ir usando las categorías.
Son las rutas:
PUT ---> http://localhost:3001/categorias/create <---- para llenar la DB
GET ----> http://localhost:3001/categorias <---- todas las categorias de la DB
DELETE ----> http://localhost:3001/categorias/create <---- para eliminar una categoría (Recibe "id" por query)

Rutas de las categorias

---

client/src/App.js
client/src/Components/Banner/Banner.jsx
client/src/Components/Home/Home.jsx

si rompe deberia ser poco

---

api/src/Models/Categorias.js
api/src/Routes/Admin/Categorias.js
api/src/Routes/Admin/Productos.js
api/src/Routes/Categories/indexCategories.js
client/src/Components/ProductCarousel/Carousel.jsx

eso, pequeño, edite la base de datos para agregar las imágenes e hice las conexiones para que entregue las categorías, a mi no me rompió nada, (ya no rompe si abrimos el home sin productos)

agregados y arreglando pequeño error del carousel

---

client/src/Components/Navbar/Navbar.jsx
client/src/Components/Product/FavoriteButton.jsx

solo añadi un mensaje para pedir que se inicie sesión antes de añadir algo a favoritos si no se esta registrado

pequeños cambios visuales a wishlist

---

api/src/Routes/Admin/Productos.js
api/src/Routes/Filters/indexFilters.js
client/src/App.js
client/src/Components/CategoryCard/CategoryCard.jsx
client/src/Components/Filtros_Ordenamientos/Filtros_Ordenamienetos.jsx
client/src/Components/Paginado/Paginado.jsx
client/src/Components/Paginado/Paginado.module.css
client/src/Components/Tienda/Tienda.jsx

solo tiene un pequeño detalle grafico cuando se cambia de categoría, mañana lo soluciono, si sigo avanzando ahora me voy a quedar atrás con el repo.
manden sus aproveesss

avance demasiado, ya casi esta funcionando como deberia

---

client/src/Components/ProductDetails/ProductDetail.jsx
client/src/Components/Review/Review.jsx
client/src/Components/ReviewCard/ReviewCard.jsx
client/src/Components/ReviewStars/ReviewStars.jsx

- Ahora el componente Detalle de producto muestra las estrellas dependiendo de las reviews
- Arreglo de estilos y otras cosas para el Componente Review y el Componente ReviewCard
- Se agrego Scroll en Detalle de Producto Ahora se puede agregar varias reviews!

Componente reviews

---

client/src/App.js
client/src/Components/AddToCardComponents/AddToCart.jsx
client/src/Components/AddToCardComponents/AddToCartIcon.jsx
client/src/Components/EditarPerfil/EditarPerfil.jsx
client/src/Components/MisCompras/MisCompras.jsx
client/src/Components/Product/Product.jsx
client/src/Components/ProductDetails/ProductDetail.jsx
client/src/Components/Review/ReviewButton.jsx

Se agrega el componente MisCompras al panel del Usuario
Se agrega el ID al localStorage 
Se agrega un botton para ir al componente Reviews desde compras
Por ahora el componente funciona tomando los datos del localStorage, en los proximos dias va a tomar los datos de mercadopago para que solo se renderizen los productos que fueron realmente comprados por el usuario.

MisCompras

---

client/src/Components/Banner/Banner.jsx
client/src/Components/Paginado/Paginado.module.css
client/src/Components/ProductCarousel/Carousel.module.css
client/src/Components/Tienda/Tienda.jsx
client/src/Components/Tienda/Tienda.module.css

cuando actualice al repo de Tom hago pruebas y subo el resto si es que no se me rompió nada.

subo solo cambios graficos ahora

---

client/src/Components/Banner/Banner.jsx
client/src/Components/Paginado/Paginado.module.css
client/src/Components/Paths/Paths.jsx
client/src/Components/ProductCarousel/Carousel.module.css
client/src/Components/ProductDetails/ProductDetail.jsx
client/src/Components/Tienda/Tienda.jsx
client/src/Components/Tienda/Tienda.module.css

el componente es el que va en detalles o en la tienda y renderiza links algo asi:
Home/products/tarjetas de video.

Componente paths o rutas

---

api/src/Models/Reviews.js
api/src/Routes/Review/review.router.js
api/src/db.js
client/src/Components/ProductDetails/ProductDetail.jsx
client/src/Components/Review/Review.jsx
client/src/Components/ReviewCard/ReviewCard.jsx
client/src/Redux/Actions/index.js

Ahora un cuando un usuario hace una review aparece su nombre en el componente ReviewCard que está en ProductDetail (pueden probar haciendo 2 cuentas y dejando su review en un producto haha)
**NOTAS**
- Se agregó un nuevo campo a la base de datos para insertar el nombre del usuario en la review
- Se agregaron los datos necesarios en las rutas del componente Review en el back para poder crear la review en la db
- Cambios en Review y Review Card para mostrar el nombre del usuario y obtener su id (Esto para mostrar el nombre en product Description)
- Se agregó la info que se envía al back en las actions
**Ahora es necesario estar loggeado para dejar una review**

Manu branch

---

client/src/Components/Filtros_Ordenamientos/Filtros_Ordenamienetos.jsx
client/src/Components/MercadoPago/FormularioPago.jsx

Se cambiaron algunos estilos del componente,
se mejoro el funcionamiento de las validaciones,
se cambio el renderizado de los errores,
se podría refactorizar para reducir la cantidad de código, pero seria un desperdicio de tiempo porque seguiría usando los mismo recursos y no cambiaria prácticamente nada xd

mejora de componente formulario de pago

---

api/src/Models/Pedidos.js
api/src/Routes/controllers/user_cuenta/compras.js
api/src/Routes/controllers/user_cuenta/comprasUsuario.js
api/src/Routes/controllers/user_cuenta/pago.js
api/src/Routes/indexUser.js
client/src/Components/Carrito/Carrito.jsx
client/src/Components/MercadoPago/MercadoPago.jsx
client/src/Components/MisCompras/MisCompras.jsx
client/src/Components/Navbar/Navbar.jsx
client/src/Components/Review/ReviewButton.jsx

Mercado pago terminado, hay que probar con el deploy y acomodar en base a eso.

MercadoPago

---

client/src/Components/MensajesAutomaticos/MensajesAutomaticos.jsx

Es un componente totalmente nuevo, así que no causara ningún conflictos porque no esta integrado a ninguna ruta.
la idea es a futuro darle a los admins la capacidad de modificar sus preguntas y respuestas, y expandir su inteligencia agregando mas palabras claves.
Tiene algunas preguntas pre definidas.
y de momento solo para pruebas reacciona a la palabra "envíos" del input.
tiene muchas posibilidades de mejora, y capaz nos da mas puntos en el PF, denle amor!

componente para ayudar al usuario, luego lo hago mas inteligente

---

api/index.js
api/src/Routes/Admin/Productos.js
api/src/Routes/controllers/user_cuenta/compras.js
api/src/Routes/controllers/user_cuenta/pago.js
api/src/Routes/indexUser.js
client/src/Components/Home/Home.jsx
client/src/Components/MercadoPago/FormularioPago.jsx
client/src/Components/Product/FavoriteButton.jsx
client/src/Components/ProductDetails/ProductDetail.jsx

Cambios en mercadopago para probar en el deploy

MercadoPago Deploy

---

api/src/Models/Categorias.js
api/src/Routes/Categories/indexCategories.js
api/src/Routes/controllers/user_cuenta/compras.js
api/src/Routes/controllers/user_cuenta/pago.js
api/src/helpers/emailCompraUser.js
api/src/helpers/emailPagoDenegado.js
client/src/Components/Footer/Footer.jsx
client/src/Components/ProductDetails/ProductDetail.jsx

Cambios en componente product detail para ver las especificaciones
Link en footer para ir al mapa
Mails de pago agregados, cuando se confirma y cuando falla la orden
ATENCION: Esto no funciona en el localhost, es para el deploy. Para que funcione en local hay que bacer unos cambios minimos, preguntar a mandrox o ami

Mail de Pago

---

client/src/Components/Home/Home.jsx
client/src/Components/MensajesAutomaticos/MensajesAutomaticos.jsx

El bot ya esta en el home, debería de funcionar bien.

ahi el chatbot ya esta integrado, seguro tiene faltas horrorgraficas

---

api/src/Routes/controllers/user_cuenta/compras.js
api/src/Routes/controllers/user_cuenta/pago.js
client/src/App.js
client/src/Components/PagoMercadiLibre/PagoAprevado/PagoConfirmado.jsx

Agrego unos cambios en las rutas de la compra, para capturar bien la direccion del usuario en cada pedido, para poder trabajar con eso para agregar las direcciones por defecto y no tener que completar el formulario cada vez que se hace un pedido.

Captura Direccion

---

client/src/Components/Banner/Banner.jsx
client/src/Components/Filtros_Ordenamientos/Filtros_Ordenamienetos.jsx
client/src/Components/Filtros_Ordenamientos/Filtros_Ordenamientos.module.css
client/src/Components/FrontPageSlide/FrontPageSlide.module.css
client/src/Components/Home/Home.jsx
client/src/Components/Paginado/Paginado.module.css
client/src/Components/Tienda/Tienda.jsx
client/src/Components/Tienda/Tienda.module.css

Son varias modificaciones para adaptar el es estilo y el funcionamiento de algunos componentes según el tamaño de la pantalla en la cual se estén visualizando (no solo teléfonos móviles),
faltarían algunos que no toque porque necesito estar seguro que nadie esta trabajando en ellos.

avance de responsive faltaria detalles y los botones de las cards

---

client/src/Components/Map/Map.jsx
client/src/Components/Product/FavoriteButton.jsx
client/src/Components/ProductDetails/ProductDetail.jsx

costo un poco pero va bien aparentemente.
Pull #100
hay que celebrar jajaja

responsive del detalle

---

api/src/Models/Pedidos.js
api/src/Routes/controllers/user_cuenta/pedidosAdmin.js
api/src/Routes/indexAdmin.js
api/src/db.js
api/src/helpers/emailCompraCompletada.js
client/src/App.js
client/src/Components/AdminPanel/DetallePedido/DetallePedido.jsx
client/src/Components/AdminPanel/Ordenes/Ordenes.jsx
client/src/Components/MisCompras/MisCompras.jsx

Se agrega el control de pedidos en el panel de admin
En la pestaña orders se muestran todos los pedidos realizados por los usuarios, se pueden filtrar por estado.
Haciendo click en modificar pedido, se muestra el detalle de cada pedido y se puede modificar su estado, una vez modificado cambia de color en el panel de orders.
El componente mis compras ahora muestra el estado de tu pedido.
Se manda un mail a cada usuario cuando se asigna "Completado" al estado de un pedido.

Admin pedidos

---

client/src/Components/MensajesAutomaticos/MensajesAutomaticos.jsx
client/src/Components/Paginado/Paginado.jsx
client/src/Components/Paginado/Paginado.module.css
client/src/Components/Product/Product.jsx
client/src/Components/Review/Review.jsx
client/src/Components/WishList/WishList.jsx

se agregaron los ordenamientos a las Wishlist.
se modificaron componentes para que sean totalmente responsivo.
y se borraron ciertas cosas comprometedoras. xd
también se mejoro el diseño del paginado, ahora solo se muestra un máximo de 3 paginas, un mínimo de 2 paginas y la pagina seleccionada se representa en pantalla. (por consejo de un usuario) xd

completando ordenamientos de wishlist faltantes y mas responsive

---

client/src/Components/Carrito/Carrito.jsx
client/src/Components/DireccionUser/DireccionUser.jsx
client/src/Components/MercadoPago/MercadoPago.jsx

-Se Creo el componente "DireccionUser".
-Se modificó el componente Carrito para mostrar los datos del envío al cliente (componente DireccionUser).
-La direccion que se guardará será la usada en la última compra.
-También se agregó una línea de código al componente MercadoPago

DatosDeEnviosAlCarrito

---

api/src/Routes/controllers/Owener/perfilUser.js
api/src/Routes/controllers/admin_productos/comprasUsuario.js
api/src/Routes/controllers/login/registo.js
api/src/Routes/controllers/user_cuenta/updateInformacion.js
api/src/Routes/indexAdmin.js
client/src/App.js
client/src/Components/AdminPanel/Users/Users.jsx
client/src/Components/EditarPerfil/EditarPerfil.jsx
client/src/Components/Login/Login.jsx
client/src/Components/OwnerPanel/PerfilUserOwner/PerfilUserOwner.jsx
client/src/Context/AuthProviderAdmin.jsx
client/src/Context/AuthProviderUsers.jsx
client/src/helper/Alerta.jsx

El usuario puede editar su perfil, imagen, nombre,direccion,correo,etc

Editar-Perfil

---

client/src/Components/AddToCardComponents/AddToCart.jsx
client/src/Components/ProductDetails/ProductDetail.jsx

ahora esta el boton para añadir una revier en el product detail y solo funcina si ya se compro el producto, de lo contrario tira un mensaje para comprar el producto

Boton añadir review

---

client/src/Components/MiniCard/MiniCard.jsx

Nada mas, si tiene que agregarse de otra forma siéntanse libres de modificar ese boton en la minicard

boton para agregar al carrito en mini card

---

api/src/db.js
client/src/Components/AddToCardComponents/AddToCart.jsx
client/src/Components/AddToCardComponents/AddToCartIcon.jsx
client/src/Components/Product/Product.jsx
client/src/Components/ProductDetails/ProductDetail.jsx

se arregla el error del productdetail
se agrega una alerta al agregar al carrito
si queda solo 1 en stock, aparece un mensaje en la card del producto.
se muestra la cantidad de unidades disponibles en el detalle, si hay una sola, aprece un mensaje correspondiente.

correciondetail

---

client/src/Components/Product/Product.jsx

pequeño cambio, nada del otro mundo

Ultima unidad ya no cambia la direccion de los elementos en la card

---

client/src/Components/ProductDetails/ProductDetail.jsx

haciendo responsivo el nuevo boton de detalles

---

api/src/Models/Bot_clave_respuesta.js
api/src/Models/Bot_opcion_respuesta.js
api/src/Routes/Chatbot/Chatbot.js
api/src/Routes/index.js
api/src/db.js

solo se modifico la db y el index de rutas para agregar estos cambios.
el resto son documentos nuevos.

primera parte del chatbot, osea backend

---

client/src/Components/ChatbotForm/ChatbotForm.jsx
client/src/Components/MensajesAutomaticos/MensajesAutomaticos.jsx

Listo el formulario debería de funcionar perfectamente, aun así, errar es humano así que seguro algo se me escapo.
Si tienen ganas de probarlo monten el componente en alguna ruta libre,
ahora solo faltaría ponerle un botón de ayuda para dar instrucciones de como agregar editar eliminar etc... ( por las dudas xd).
Luego hay que pasarlo a una ruta protegida para que solo el admin pueda modificar el chatbot.

formulario del chatbot funcionando

---

api/src/Routes/Chatbot/Chatbot.js
api/src/Routes/Chatbot/ChatbotAdmin.js
api/src/Routes/indexAdmin.js
client/src/Redux/Actions/index.js

listo, ya esta en rutas protegidas, solo falta agregarlo al panel del admin.
del resto funciona bien!

Protegiendo chatbot
